// examples/svelte/src/App.svelte
<script>
import { tilt } from "@levita-js/svelte";
import "@levita-js/core/style.css";
</script>

<div class="container">
  <div use:tilt={{ glare: true, maxGlare: 0.5, shadow: true }} class="card">
    Svelte
  </div>
</div>

<style>
  .container {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100vh;
    font-family: system-ui, sans-serif;
  }
  .card {
    width: 300px;
    height: 400px;
    background: linear-gradient(135deg, #ff3e00 0%, #ffbe00 100%);
    border-radius: 20px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 2rem;
    font-weight: bold;
    box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
  }
</style>

// examples/react/src/App.tsx
import { Tilt } from "@levita-js/react";
import "@levita-js/core/style.css";

function App() {
	const cardStyle = {
		width: "300px",
		height: "400px",
		background: "linear-gradient(135deg, #3b82f6 0%, #2dd4bf 100%)",
		borderRadius: "20px",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		color: "white",
		fontSize: "2rem",
		fontWeight: "bold",
		boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.5)",
	};

	const containerStyle = {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		height: "100vh",
		fontFamily: "system-ui, sans-serif",
	};

	return (
		<div style={containerStyle}>
			<Tilt glare maxGlare={0.5} shadow style={{ borderRadius: "20px" }}>
				<div style={cardStyle}>React</div>
			</Tilt>
		</div>
	);
}

export default App;
